kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage-claim
  namespace: ${PING_IDENTITY_K8S_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2