{
 "title": "Kubernetes Cluster Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod and container statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "All processes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "All processes CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "All processes memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  { "title": "Containers network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Containers network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "All processes network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}
{
 "title": "PingDirectory Per-Server Dashboard",
 "description": "PingDirectory Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "${PING_IDENTITY_K8S_NAMESPACE}" }
  ]
 },
 "panels": [
  {
   "title": "Throughput by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput by Operation and Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "throughput{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Average Operation Latency by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (response_time{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Latency by Operation and Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "response_time{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Collections per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (gcType, size, cause, instance) (rate(garbage_collections{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}-{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  },
  {
   "title": "GC Live Megabytes by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "PingIdentity Performance Test",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "$PING_IDENTITY_K8S_NAMESPACE" },
   { "name": "range_interval", "label": "range_interval", "query": "1m" },
   { "name": "data_source", "query": "influxdb" },
   { "name": "jm_database", "query": "SHOW DATABASES" },
   {
    "name": "jm_measurement",
    "query": "SHOW MEASUREMENTS ON \"$jm_database\""
   },
   {
    "name": "jm_retention",
    "query": "SHOW RETENTION POLICIES on \"$jm_database\""
   },
   {
    "name": "jm_application",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"application\""
   },
   {
    "name": "jm_transaction",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"transaction\""
   },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - Client (j)",
   "type": "singlestat",
   "description": "failed requests for *all* transactions of a single measurement",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate % - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Response Times 99,95,90% - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "90%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxAT\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'internal' AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage % - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name=~\"$server\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (%) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!~\"ping.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container_name!=\"POD\",pod!~\"ping.*\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name!~\"ping.*\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated Resources per Container - Server (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    }
   ]
  },
  {
   "title": "Load Generator Resources Allocated - Client (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    }
   ]
  },
  {
   "title": "Network io bytes out - Server/client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod!=\"\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network io bytes in - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$server.*\"}[1m])) by (pod)"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU - # of cores - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$server\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!~\"ping.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod_name!~\"ping.*\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total Errors - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by Transaction - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "modify",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~/^Mod.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "bind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Bind.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "search",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Search.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by client - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  application,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors per Transaction - Client (j)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 }
  },
  { "title": "Error Info - Client (j)", "type": "table", "gridPos": { "h": 7, "w": 16, "x": 8, "y": 53 } }
 ]
}
{
 "title": "PingDirectory Performance Test",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "$PING_IDENTITY_K8S_NAMESPACE" },
   { "name": "range_interval", "label": "range_interval", "query": "1m" },
   { "name": "data_source", "query": "influxdb" },
   { "name": "jm_database", "query": "SHOW DATABASES" },
   {
    "name": "jm_measurement",
    "query": "SHOW MEASUREMENTS ON \"$jm_database\""
   },
   {
    "name": "jm_retention",
    "query": "SHOW RETENTION POLICIES on \"$jm_database\""
   },
   {
    "name": "jm_application",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"application\""
   },
   {
    "name": "jm_transaction",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"transaction\""
   },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Throughput by Operation - Server (p)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Received Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - Client (j)",
   "type": "singlestat",
   "description": "failed requests for *all* transactions of a single measurement",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate % - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Response Times 99,95,90% - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "90%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxAT\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'internal' AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage % - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name=\"pingdirectory\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (%) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!~\"pingdirectory.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container_name!=\"POD\",pod!~\"pingdirectory.*\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name!=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container!=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated Resources per Container - Server (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    }
   ]
  },
  {
   "title": "Load Generator Resources Allocated - Client (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container!~\"ping.*\",namespace=\"$namespace\"})by (pod)"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container!~\"ping.*\",namespace=\"$namespace\"})by (pod))/1073741824"
    }
   ]
  },
  {
   "title": "Network io bytes out - Server/client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod!=\"\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network io bytes in - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"pingdirectory.*\"}[1m])) by (pod)"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU - # of cores - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"pingdirectory\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Avg DB Cache % Full by Backend - Server (p)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(backend_db_cache_percent_full{namespace=\"$namespace\"}) by (backendID)"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!~\"pingdirectory.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod_name!~\"pingdirectory.*\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "DB Cache % Full by Backend and Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(backend_db_cache_percent_full{namespace=\"$namespace\"}) by (backendID,instance)",
     "legendFormat": "{{backendID}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Checkpoint Duration by Backend and Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backend_avg_checkpoint_duration{namespace=\"$namespace\"}",
     "legendFormat": "{{backendID}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Checkpoint Duration by Backend and Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(backend_avg_checkpoint_duration{namespace=\"$namespace\"}) by (backendID)",
     "legendFormat": "{{backendID}}-avg"
    }
   ]
  },
  {
   "title": "Worker Threads Busy - Server (p)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(worker_threads_busy{namespace=\"$namespace\"})by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Backlog - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Backlog" }
   ],
   "targets": [
    {
     "expr": "_dc_example{dc=\"com\\\".replica-backlog\",namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ops in Progress - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ops_in_progress", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connections and New Connections - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connections", "legendFormat": "{{instance}}-connection" },
    { "expr": "new_connections", "legendFormat": "{{instance}}-new" }
   ]
  },
  {
   "title": "Average Entry Count by Backend - Server (p)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Entry Count" }
   ],
   "targets": [
    {
     "expr": "avg by (backendID) (backend_entry_count{namespace=\"$namespace\"})",
     "legendFormat": "{{backendID}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Overall Operation Throughput - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum(throughput{namespace=\"$namespace\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Total Throughput by Operation - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Throughput per Operation and Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "throughput{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Throughput per Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Throughput by operation - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "modify",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~/^Mod.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "bind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Bind.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "search",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Search.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by client - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  application,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Rate per Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Collections per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (gcType, size, cause, instance) (rate(garbage_collections{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}-{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  },
  {
   "title": "GC Live Megabytes per Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average GC Live Megabytes by Region - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "avg by (region) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Response Times (99th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "all_transactions",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND transaction='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (95th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (90th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (99th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND transaction !='all') AND $timeFilter GROUP BY  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (95th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (90th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Average Latency by Server - Server (p)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Latency (ms)" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (response_time{namespace=\"$namespace\"} > 0)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Overall Average Operation Latency - Server (p)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Latency (ms)" }
     ],
     "targets": [
      {
       "expr": "avg((response_time{namespace=\"$namespace\"} > 0))"
      }
     ]
    },
    {
     "title": "Average Latency by Operation and Server - Server (p)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Latency (ms)" }
     ],
     "targets": [
      {
       "expr": "response_time{namespace=\"$namespace\"} > 0",
       "legendFormat": "{{instance}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Average Latency by Operation - Server (p)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Latency (ms)" }
     ],
     "targets": [
      {
       "expr": "avg by (operation) (response_time{namespace=\"$namespace\"} > 0)",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    { "title": "Error Info - Client (j)", "type": "table", "gridPos": { "h": 7, "w": 16, "x": 8, "y": 5 } },
    {
     "title": "Errors per Transaction - Client (j)",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 }
    }
   ]
  }
 ]
}