apiVersion: v1
data:
  CLUSTER_BIND_ADDRESS: NON_LOOPBACK
  CLUSTER_NAME: tmp-pdog
  DNS_QUERY_LOCATION: _bind-port._tcp.pf-cluster.tmp-pdog.svc.cluster.local
  DNS_RECORD_TYPE: SRV
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
  PF_ADMIN_PUBLIC_HOSTNAME: pingfederate-admin.anydevops.com
  PF_ENGINE_PUBLIC_HOSTNAME: pingfederate.anydevops.com
  PF_ENGINE_PUBLIC_PORT: "443"
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_BASELINE_PARENT: MONITOR
  SERVER_PROFILE_BASELINE_PATH: baseline/pingfederate
  SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_MONITOR_PATH: monitoring/pingfederate/jolokia-simple
  SERVER_PROFILE_MONITOR_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_PARENT: BASELINE
  SERVER_PROFILE_PATH: pf-dns-ping-clustering/pingfederate
  SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: pingfederate-admin-environment-variables
---
apiVersion: v1
data:
  CLUSTER_BIND_ADDRESS: NON_LOOPBACK
  CLUSTER_NAME: tmp-pdog
  DNS_QUERY_LOCATION: _bind-port._tcp.pf-cluster.tmp-pdog.svc.cluster.local
  DNS_RECORD_TYPE: SRV
  OPERATIONAL_MODE: CLUSTERED_ENGINE
  PF_ADMIN_PUBLIC_HOSTNAME: pingfederate-admin.anydevops.com
  PF_ENGINE_PUBLIC_HOSTNAME: pingfederate.anydevops.com
  PF_ENGINE_PUBLIC_PORT: "443"
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_BASELINE_PARENT: MONITOR
  SERVER_PROFILE_BASELINE_PATH: baseline/pingfederate
  SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_MONITOR_PATH: monitoring/pingfederate/jolokia-simple
  SERVER_PROFILE_MONITOR_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_PARENT: BASELINE
  SERVER_PROFILE_PATH: pf-dns-ping-clustering/pingfederate
  SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: pingfederate-engine-environment-variables
---
apiVersion: v1
data:
  telegraf.conf: |
    [global_tags]
      env = "$ENV"
    [agent]
      ## interval - this may be something to increase back to 1s
      interval = "5s"
      ## made this false to avoid conflicting collection/reporting times
      round_interval = false
      metric_batch_size = 10000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      debug = true
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false
    [[inputs.cpu]]
      ## Whether to report per-cpu stats or not
      percpu = true
      ## Whether to report total system cpu stats or not
      totalcpu = true
      ## If true, collect raw CPU time metrics.
      collect_cpu_time = false
      ## If true, compute and report the sum of all non-idle CPU states.
      report_active = false
    [[inputs.mem]]
    [[inputs.jolokia2_agent]]
      urls = ["https://localhost:9031/jolokia"]
      insecure_skip_verify = true
      tagexclude = ["jolokia_agent_url"]
    [[inputs.jolokia2_agent.metric]]
        name  = "java_runtime"
        mbean = "java.lang:type=Runtime"
        paths = ["Uptime"]
    [[inputs.jolokia2_agent.metric]]
        name  = "java_memory"
        mbean = "java.lang:type=Memory"
        paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]
    [[inputs.jolokia2_agent.metric]]
        name     = "java_garbage_collector"
        mbean    = "java.lang:name=*,type=GarbageCollector"
        paths    = ["CollectionTime", "CollectionCount"]
        tag_keys = ["name"]
    [[inputs.jolokia2_agent.metric]]
        name  = "java_last_garbage_collection"
        mbean = "java.lang:name=*,type=GarbageCollector"
        paths = ["LastGcInfo"]
        tag_keys = ["name"]
    [[inputs.jolokia2_agent.metric]]
        name  = "java_threading"
        mbean = "java.lang:type=Threading"
        paths = ["TotalStartedThreadCount", "ThreadCount", "CurrentThreadCpuTime", "DaemonThreadCount", "PeakThreadCount"]
    [[inputs.jolokia2_agent.metric]]
        name  = "java_class_loading"
        mbean = "java.lang:type=ClassLoading"
        paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]
    [[inputs.jolokia2_agent.metric]]
        name     = "java_memory_pool"
        mbean    = "java.lang:name=*,type=MemoryPool"
        paths    = ["Usage", "PeakUsage", "CollectionUsage"]
        tag_keys = ["name"]
    [[inputs.jolokia2_agent.metric]]
        name    = "host"
        mbean   = "pingfederate:type=*"
        paths   = ["Count"]
    [[inputs.jolokia2_agent.metric]]
        name     = "jetty_connector_stats"
        mbean    = "org.eclipse.jetty.server:context=*,id=*,type=connectorstatistics"
        paths    = ["bytesIn","bytesOut","connections","connectionsOpen","connectionsOpenMax","connectionDurationMean","connectionDurationMax","connectionDurationStdDev","messagesOutPerConnectionMax","messagesOutPerConnectionMean","messagesOutPerConnectionStdDev","messagesOutPerSecond","messagesInPerConnectionMax","messagesInPerConnectionMean","messagesInPerConnectionStdDev","messagesInPerSecond"]
    [[inputs.jolokia2_agent.metric]]
        name     = "jetty_connector_resources"
        mbean    = "com.pingidentity.appserver.jetty.server.connector:context=*,id=*,type=serverconnector"
        paths    = ["acceptQueueSize","acceptors"]
    [[outputs.prometheus_client]]
      listen = ":9273"
kind: ConfigMap
metadata:
  name: telegraf-conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    role: pingfederate
  name: pf-cluster
spec:
  clusterIP: None
  ports:
  - name: bind-port
    port: 7600
    protocol: TCP
    targetPort: 7600
  publishNotReadyAddresses: true
  selector:
    role: pingfederate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingfederate
    tier: engine
  name: pingfederate
spec:
  ports:
  - name: https
    port: 9031
  - name: telegraf
    port: 9273
  selector:
    role: pingfederate
    tier: engine
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingfederate
    tier: console
  name: pingfederate-admin
spec:
  ports:
  - name: pf-console
    port: 9999
  selector:
    role: pingfederate
    tier: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingfederate
    tier: engine
  name: pingfederate
spec:
  replicas: 2
  selector:
    matchLabels:
      role: pingfederate
      tier: engine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: pingfederate
        tier: engine
        version: "0.1"
      name: pingfederate
    spec:
      containers:
      - env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: docker.io/library/telegraf:1.9.5-alpine
        name: ping-telegraf
        ports:
        - containerPort: 9273
          name: telegraf
        resources:
          limits:
            cpu: 15m
            memory: 50M
          requests:
            cpu: 15m
            memory: 50M
        volumeMounts:
        - mountPath: /etc/telegraf
          name: telegraf-conf
      - envFrom:
        - configMapRef:
            name: pingfederate-engine-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingfederate:latest
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 20
        name: pingfederate
        ports:
        - containerPort: 9031
        readinessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 10
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
      initContainers:
      - command:
        - sh
        - -c
        - until curl --connect-timeout 1 --silent -k https://pingfederate-admin:9999/pingfederate/app
          ; do echo waiting for admin ; sleep 2 ; done
        image: curlimages/curl:latest
        name: init
      volumes:
      - configMap:
          name: telegraf-conf
        name: telegraf-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingfederate
    tier: console
  name: pingfederate-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingfederate
      tier: console
  template:
    metadata:
      labels:
        role: pingfederate
        tier: console
      name: pingfederate-admin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingfederate-admin-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingfederate:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /pingfederate/app
            port: 9999
            scheme: HTTPS
          initialDelaySeconds: 100
          periodSeconds: 1
        name: pingfederate-admin
        ports:
        - containerPort: 9999
        - containerPort: 7600
        readinessProbe:
          httpGet:
            path: /pingfederate/app
            port: 9999
            scheme: HTTPS
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until curl --connect-timeout 1 --silent -k https://pingdirectory:443/directory/v1
          ; do echo waiting for admin ; sleep 2 ; done
        image: curlimages/curl:latest
        name: init
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    role: pingfederate
    tier: engine
  name: pingfederate
spec:
  rules:
  - host: pingfederate.samir.ping-devops.com
    http:
      paths:
      - backend:
          serviceName: pingfederate
          servicePort: 9031
        path: /
  tls:
  - hosts:
    - pingfederate.samir.ping-devops.com
    secretName: tls-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    role: pingfederate
    tier: admin
  name: pingfederate-admin
spec:
  rules:
  - host: pingfederate-admin.samir.ping-devops.com
    http:
      paths:
      - backend:
          serviceName: pingfederate-admin
          servicePort: 9999
        path: /pingfederate
      - backend:
          serviceName: pingfederate-admin
          servicePort: 9999
        path: /pf-admin-api
  tls:
  - hosts:
    - pingfederate-admin.samir.ping-devops.com
    secretName: tls-secret
