kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- https://github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/06-clustered-pingfederate
- ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-engine-environment-variables
  behavior: replace
  envs:
    - env_vars.pingfederate-engine
- name: pingfederate-admin-environment-variables
  behavior: replace
  envs:
    - env_vars.pingfederate-admin

