{
 "title": "PingDirectory Performance Test",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "perf-pingdirectory" },
   { "name": "range_interval", "label": "range_interval", "query": "5m" },
   { "name": "data_source", "query": "influxdb" },
   { "name": "jm_database", "query": "SHOW DATABASES" },
   {
    "name": "jm_measurement",
    "query": "SHOW MEASUREMENTS ON \"$jm_database\""
   },
   {
    "name": "jm_retention",
    "query": "SHOW RETENTION POLICIES on \"$jm_database\""
   },
   {
    "name": "jm_application",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"application\""
   },
   {
    "name": "jm_transaction",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"transaction\""
   },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Throughput by Operation - Server",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "99th% Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ ) AND $timeFilter GROUP BY \"transaction\",time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th% Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ ) AND $timeFilter GROUP BY \"transaction\",time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "90th% Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ ) AND $timeFilter GROUP BY \"transaction\",time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "description": "failed requests for *all* transactions of a single measurement",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput (Client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxAT\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'internal' AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated Resources per Container",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) group_left(nodegroup) (0 * label_replace(\n    (kube_node_labels),\n    \"nodegroup\",\"$1\",\"label_alpha_eksctl_io_nodegroup_name\",\"(.+)\"\n  ))"
    }
   ]
  },
  {
   "title": "Containers producing traffic",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container!=\"pingdirectory\",namespace=\"$namespace\"})by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{container!=\"pingdirectory\",namespace=\"$namespace\"})by (pod)/1073741824"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU usage % - Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name=\"pingdirectory\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (%) - Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network io bytes in - Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"pingdirectory.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"pingdirectory\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Average Entry Count by Backend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Entry Count" }
   ],
   "targets": [
    {
     "expr": "avg by (backendID) (backend_entry_count{namespace=\"$namespace\"})",
     "legendFormat": "{{backendID}}"
    }
   ]
  },
  {
   "title": "CPU usage % - Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name!=\"pingdirectory\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container!=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used % - Client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name!=\"pingdirectory\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container!=\"pingdirectory\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Overall Operation Throughput (Server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum(throughput{namespace=\"$namespace\"})",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Total Throughput (Client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by Operation - Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Throughput by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Throughput (Client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY  \"application\",time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput by Operation and Server (Server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "throughput{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Replication Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Backlog" }
   ],
   "targets": [
    {
     "expr": "_dc_example{dc=\"com\\\".replica-backlog\",namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Collections per Minute" }
   ],
   "targets": [
    {
     "expr": "sum by (gcType, size, cause, instance) (rate(garbage_collections{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}-{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  },
  {
   "title": "GC Live Megabytes by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average GC Live Megabytes by Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "avg by (region) (garbage_collection_live_megabytes{namespace=\"$namespace\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Transactions Response Times (99th pct)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (90th pct)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Operation Latency by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (response_time{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Latency by Operation and Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "response_time{namespace=\"$namespace\"} > 0",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Overall Average Operation Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg((response_time{namespace=\"$namespace\"} > 0))"
    }
   ]
  },
  {
   "title": "Average Latency by Operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "avg by (operation) (response_time{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors per Transaction",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"statut\" = 'ko') AND $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT * FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"responseCode\" != ''  AND $timeFilter)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}