{
 "title": "PingIdentity Performance Test - r/w",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "$PING_IDENTITY_K8S_NAMESPACE" },
   { "name": "range_interval", "label": "range_interval", "query": "1m" },
   { "name": "data_source", "query": "influxdb" },
   { "name": "jm_database", "query": "SHOW DATABASES" },
   {
    "name": "jm_measurement",
    "query": "SHOW MEASUREMENTS ON \"$jm_database\""
   },
   {
    "name": "jm_retention",
    "query": "SHOW RETENTION POLICIES on \"$jm_database\""
   },
   {
    "name": "jm_application",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"application\""
   },
   {
    "name": "jm_transaction",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"transaction\""
   },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - Client (j)",
   "type": "singlestat",
   "description": "failed requests for *all* transactions of a single measurement",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate % - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Response Times 99,95,90% - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "90%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxAT\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'internal' AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage % - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name=~\"$server\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (%) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!~\"ping.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_cpu_cores{container_name!=\"POD\",pod!~\"ping.*\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used % - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  label_replace(\n    (sum(container_memory_working_set_bytes{container_name!~\"ping.*\",namespace=\"$namespace\"}) by (pod_name)),\n    \"pod\",\"$1\",\"pod_name\",\"(.+)\"\n  )\n  / on (pod) \n  (sum(kube_pod_container_resource_requests_memory_bytes{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (pod))\n)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocated Resources per Container - Server (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{container=~\"$server\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    }
   ]
  },
  {
   "title": "Load Generator Resources Allocated - Client (k)",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (node,pod)) + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{container!~\"ping.*\",node!=\"\",namespace=\"$namespace\"}) by (node,pod))/1073741824 + on(node) \ngroup_left(nodegroupNzone) (0 * label_join(\n    kube_node_labels,\n    \"nodegroupNzone\",\", \",\"label_alpha_eksctl_io_nodegroup_name\",\"label_failure_domain_beta_kubernetes_io_zone\"\n  ))"
    }
   ]
  },
  {
   "title": "Network io bytes out - Server/client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod!=\"\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network io bytes in - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$server.*\"}[1m])) by (pod)"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU - # of cores - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"$server\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!~\"ping.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod_name!~\"ping.*\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total Errors - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by Transaction - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "modify",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~/^Mod.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "bind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Bind.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "search",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Search.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by client - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  application,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors per Transaction - Client (j)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 }
  },
  { "title": "Error Info - Client (j)", "type": "table", "gridPos": { "h": 7, "w": 16, "x": 8, "y": 53 } }
 ]
}