apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  storageClassName: gp2
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2

